version: '3.8'

services:
  minio:
    image: bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - networks_name
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=user_name
      - MINIO_ROOT_PASSWORD=pass_min8
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
      - MINIO_DEFAULT_BUCKETS=bucket_name

  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_name
    networks:
      - networks_name

networks:
  networks_name:
    driver: bridge

volumes:
  minio_data:
